import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ru";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    welcome: "WELCOME TO SPARKAPH",
    select_chat: "SELECT A CHAT TO START MESSAGING",
    search: "SEARCH...",
    online: "ONLINE",
    offline: "OFFLINE",
    was_online: "WAS ONLINE",
    type_message: "TYPE A MESSAGE...",
    profile_settings: "PROFILE SETTINGS",
    username: "USERNAME",
    avatar_url: "AVATAR URL",
    bio: "BIO",
    relationship_status: "RELATIONSHIP STATUS",
    notifications: "NOTIFICATIONS",
    save: "SAVE",
    back_to_chat: "BACK TO CHAT",
    upload_avatar: "CLICK TO UPLOAD AVATAR",
    single: "Single",
    dating: "Dating",
    married: "Married",
    complicated: "It's complicated",
    searching: "Active searching",
    not_specified: "Not specified",
    about_me: "ABOUT ME",
    unknown_user: "Unknown User",
    group_chat: "Group Chat",
    voice_message: "Voice Message",
    sticker: "Sticker",
    new_message_from: "New message from",
    browser_not_supported: "This browser does not support notifications",
    profile_updated: "Profile updated successfully!",
    logout: "LOGOUT",
    settings: "SETTINGS",
    login: "LOGIN",
    register: "REGISTER",
    email: "EMAIL",
    password: "PASSWORD",
    confirm_password: "CONFIRM PASSWORD",
    already_have_account: "Already have an account?",
    dont_have_account: "Don't have an account?",
    passwords_dont_match: "Passwords do not match",
    registration_failed: "Registration failed",
    login_failed: "Login failed",
    calling: "Calling...",
    incoming_call: "Incoming Call...",
    video_call: "Video Call",
    audio_call: "Audio Call",
    answer: "Answer",
    decline: "Decline",
    end_call: "End Call",
    create_app: "Create App",
    no_apps_yet: "No apps yet. Create your first app!",
    deployed: "Deployed",
    building: "Building...",
    waiting_zip: "Waiting for ZIP",
    failed: "Failed",
    no_deployment: "No deployment",
    upload_zip: "Upload ZIP",
    app_name: "App Name",
    app_handle: "App Handle",
    app_description: "App Description",
    app_type: "App Type",
    hosted: "Hosted",
    external: "External",
    create_app_modal: "Create App",
    deploy_method: "Deploy Method",
    instant_deploy: "Instant Deploy",
    zip_upload: "ZIP Upload",
    url_deploy: "URL Deploy",
    github_deploy: "GitHub Deploy",
    instant_html: "HTML Code",
    external_url: "External URL",
    github_repo: "GitHub Repository",
    create_app_upload_later: "Create App (Upload ZIP Later)",
    upload_zip_file: "Upload ZIP File",
    upload_zip_instruction: "Upload ZIP with index.html and assets.",
    token_generation_failed: "Token generation failed. Please check API Tokens tab.",
    developer_dashboard: "Developer Dashboard",
    my_apps: "My Apps",
    api_token: "API Token",
    views: "views",
    deploy_mini_app: "Deploy Mini App",
    html_css_js_only: "HTML/CSS/JS only",
    instant: "Instant",
    url: "URL",
    zip: "ZIP",
    app_name_placeholder: "Enter app name",
    app_handle_placeholder: "Enter app handle",
    app_description_placeholder: "Describe your app",
    uploading: "Uploading...",
    app_deployed: "App deployed!",
    app_url: "URL",
    deploy_failed: "Failed to deploy app",
    create_failed: "Failed to create app",
    simple_deploy: "Simple Deploy",
    quick_deploy: "Quick Deploy",
    enter_html: "Enter HTML code",
    enter_url: "Enter external URL",
    enter_github: "Enter GitHub repo URL",
    deploy_now: "Deploy Now",
    cancel: "Cancel",
    app_created_successfully: "App Created Successfully!",
    app_ready_next_step: "is ready. Choose your next step:",
    skip_for_now: "Skip for Now",
    block_user_confirm: "Are you sure you want to block",
    user_blocked_success: "User blocked successfully",
    user_blocked_failed: "Failed to block user",
    archived: "Archived",
    archive: "Archive",
    unarchive: "Unarchive",
    archived_chat: "Archived chat",
    chats: "Chats",
    token_generated: "API Token Generated",
    copy_token: "Copy Token",
    token_copied: "Token copied to clipboard",
    update_profile: "Update your profile information",
    click_change_avatar: "Click to change avatar",
    site_avatar: "Site Avatar",
    in_app_notifications: "In-app notifications",
    access_developer_console: "Access developer console",
    save_changes: "Save Changes",
    remove: "Remove",
    welcome_back: "Welcome back",
    enter_username: "Enter your username",
    enter_password: "Enter your password",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    create_account: "Create account",
    create_your_account: "Create your account",
    nickname: "Nickname",
    choose_username: "Choose a username",
    choose_nickname: "Choose a nickname",
    create_password: "Create a password",
    followers: "Followers",
    following: "Following",
    friend: "Friend",
    message: "Message",
    unfollow: "Unfollow",
    follow: "Follow",
    about: "About",
    no_bio_yet: "No bio yet",
    online_status: "Online",
    no_followers_yet: "No followers yet",
    not_following_anyone_yet: "Not following anyone yet",
    following_user: "Following user!",
    unfollowed_user: "Unfollowed user",
    failed_to_follow_user: "Failed to follow user",
    failed_to_unfollow_user: "Failed to unfollow user",
    failed_to_fetch_followers: "Failed to fetch followers",
    failed_to_fetch_following: "Failed to fetch following",
    hosted_app: "Hosted App",
    external_app: "External App",
    hosted_app_info: "Hosted apps require ZIP file upload",
    external_app_info: "External apps connect via webhook URL",
    app_settings: "App Settings",
    delete_app_confirm: "Are you sure you want to delete this app?",
    upload_zip_required: "Please upload a .zip file",
    file_size_exceeded: "File size exceeds 50MB limit",
    zip_upload_success: "ZIP uploaded successfully!",
    zip_upload_failed: "Failed to upload ZIP. Please check the file format and try again.",
    zip_upload_connection_error: "Failed to upload ZIP. Please check your connection and try again.",
    create_app_failed: "Failed to create app",
    waiting_for_upload: "Waiting for Upload",
    app_ready_needs_zip: "This app is ready but needs a ZIP file to be uploaded. Go to Developer Console to upload your app.",
    go_to_developer_console: "Go to Developer Console",
    got_it: "Got it!",
    token_generation_failed_text: "Token generation failed. Please check API Tokens tab.",
    loading_profile: "Loading profile...",
    developer_mode: "Developer Mode",
    enable_developer_mode: "Enable Developer Mode",
    disable_developer_mode: "Disable Developer Mode",
    select_language: "Language",
    english: "English",
    russian: "Russian",
    profile: "Profile",
    dev: "Dev",
    delete_app: "Delete App",
    app_deleted: "App deleted successfully",
    delete_failed: "Failed to delete app",
    delete: "Delete",
  },
  ru: {
    welcome: "ДОБРО ПОЖАЛОВАТЬ В SPARKAPH",
    select_chat: "ВЫБЕРИТЕ ЧАТ ЧТОБЫ НАЧАТЬ ОБЩЕНИЕ",
    search: "ПОИСК...",
    online: "В СЕТИ",
    offline: "ОФФЛАЙН",
    was_online: "БЫЛ(А)",
    type_message: "НАПИШИТЕ СООБЩЕНИЕ...",
    profile_settings: "НАСТРОЙКИ ПРОФИЛЯ",
    username: "ИМЯ ПОЛЬЗОВАТЕЛЯ",
    avatar_url: "URL АВАТАРА",
    bio: "О СЕБЕ",
    relationship_status: "СЕМЕЙНОЕ ПОЛОЖЕНИЕ",
    notifications: "УВЕДОМЛЕНИЯ",
    save: "СОХРАНИТЬ",
    back_to_chat: "НАЗАД В ЧАТ",
    upload_avatar: "НАЖМИТЕ ЧТОБЫ ЗАГРУЗИТЬ АВАТАР",
    single: "Свободен/Свободна",
    dating: "Встречаюсь",
    married: "В браке",
    complicated: "Всё сложно",
    searching: "В активном поиске",
    not_specified: "Не указано",
    about_me: "О СЕБЕ",
    unknown_user: "Неизвестный пользователь",
    group_chat: "Групповой чат",
    voice_message: "Голосовое сообщение",
    sticker: "Стикер",
    new_message_from: "Новое сообщение от",
    browser_not_supported: "Этот браузер не поддерживает уведомления",
    profile_updated: "Профиль обновлен!",
    logout: "ВЫЙТИ",
    settings: "НАСТРОЙКИ",
    login: "ВОЙТИ",
    register: "РЕГИСТРАЦИЯ",
    email: "EMAIL",
    password: "ПАРОЛЬ",
    confirm_password: "ПОДТВЕРДИТЕ ПАРОЛЬ",
    already_have_account: "Уже есть аккаунт?",
    dont_have_account: "Нет аккаунта?",
    passwords_dont_match: "Пароли не совпадают",
    registration_failed: "Ошибка регистрации",
    login_failed: "Ошибка входа",
    calling: "Звонок...",
    incoming_call: "Входящий звонок...",
    video_call: "Видеозвонок",
    audio_call: "Аудиозвонок",
    answer: "Ответить",
    decline: "Отклонить",
    end_call: "Завершить",
    create_app: "Создать приложение",
    no_apps_yet: "Нет приложений. Создайте первое приложение!",
    deployed: "Развернуто",
    building: "Сборка...",
    waiting_zip: "Ожидание ZIP",
    failed: "Ошибка",
    no_deployment: "Нет деплоя",
    upload_zip: "Загрузить ZIP",
    app_name: "Название приложения",
    app_handle: "Handle приложения",
    app_description: "Описание приложения",
    app_type: "Тип приложения",
    hosted: "Хостинг",
    external: "Внешний",
    create_app_modal: "Создать приложение",
    deploy_method: "Метод деплоя",
    instant_deploy: "Мгновенный деплой",
    zip_upload: "Загрузка ZIP",
    url_deploy: "Деплой по URL",
    github_deploy: "Деплой с GitHub",
    instant_html: "HTML код",
    external_url: "Внешний URL",
    github_repo: "Репозиторий GitHub",
    create_app_upload_later: "Создать приложение (загрузить ZIP позже)",
    upload_zip_file: "Загрузить ZIP файл",
    upload_zip_instruction: "Загрузите ZIP с index.html и ресурсами.",
    token_generation_failed: "Ошибка генерации токена. Проверьте вкладку API Tokens.",
    developer_dashboard: "Панель разработчика",
    my_apps: "Мои приложения",
    api_token: "API токен",
    views: "просмотров",
    deploy_mini_app: "Развернуть мини-приложение",
    html_css_js_only: "Только HTML/CSS/JS",
    instant: "Мгновенно",
    url: "URL",
    zip: "ZIP",
    app_name_placeholder: "Введите название приложения",
    app_handle_placeholder: "Введите handle приложения",
    app_description_placeholder: "Опишите ваше приложение",
    uploading: "Загрузка...",
    app_deployed: "Приложение развернуто!",
    app_url: "URL",
    deploy_failed: "Ошибка деплоя",
    create_failed: "Ошибка создания",
    simple_deploy: "Простой деплой",
    quick_deploy: "Быстрый деплой",
    enter_html: "Введите HTML код",
    enter_url: "Введите внешний URL",
    enter_github: "Введите URL репозитория GitHub",
    deploy_now: "Развернуть",
    cancel: "Отмена",
    app_created_successfully: "Приложение создано!",
    app_ready_next_step: "готово. Выберите следующий шаг:",
    skip_for_now: "Пропустить",
    block_user_confirm: "Вы уверены, что хотите заблокировать",
    user_blocked_success: "Пользователь заблокирован",
    user_blocked_failed: "Не удалось заблокировать пользователя",
    archived: "Архив",
    archive: "Архивировать",
    unarchive: "Разархивировать",
    archived_chat: "Архивированный чат",
    chats: "Чаты",
    token_generated: "API токен сгенерирован",
    copy_token: "Копировать токен",
    token_copied: "Токен скопирован",
    update_profile: "Обновите информацию профиля",
    click_change_avatar: "Нажмите чтобы изменить аватар",
    site_avatar: "Аватар сайта",
    in_app_notifications: "Уведомления в приложении",
    access_developer_console: "Доступ к консоли разработчика",
    save_changes: "Сохранить изменения",
    remove: "Удалить",
    welcome_back: "С возвращением",
    enter_username: "Введите имя пользователя",
    enter_password: "Введите пароль",
    sign_in: "Войти",
    sign_up: "Регистрация",
    create_account: "Создать аккаунт",
    create_your_account: "Создайте свой аккаунт",
    nickname: "Никнейм",
    choose_username: "Выберите имя пользователя",
    choose_nickname: "Выберите никнейм",
    create_password: "Создайте пароль",
    followers: "Подписчики",
    following: "Подписки",
    friend: "Друг",
    message: "Сообщение",
    unfollow: "Отписаться",
    follow: "Подписаться",
    about: "О себе",
    no_bio_yet: "Нет биографии",
    online_status: "В сети",
    no_followers_yet: "Нет подписчиков",
    not_following_anyone_yet: "Никого не подписаны",
    following_user: "Подписка успешна!",
    unfollowed_user: "Отписка успешна",
    failed_to_follow_user: "Не удалось подписаться",
    failed_to_unfollow_user: "Не удалось отписаться",
    failed_to_fetch_followers: "Не удалось загрузить подписчиков",
    failed_to_fetch_following: "Не удалось загрузить подписки",
    hosted_app: "Хостинг приложение",
    external_app: "Внешнее приложение",
    hosted_app_info: "Хостинг приложения требуют загрузку ZIP файла",
    external_app_info: "Внешние приложения подключаются через webhook URL",
    app_settings: "Настройки приложения",
    delete_app_confirm: "Вы уверены, что хотите удалить это приложение?",
    upload_zip_required: "Пожалуйста загрузите .zip файл",
    file_size_exceeded: "Размер файла превышает 50MB",
    zip_upload_success: "ZIP загружен успешно!",
    zip_upload_failed: "Не удалось загрузить ZIP. Проверьте формат файла и попробуйте снова.",
    zip_upload_connection_error: "Не удалось загрузить ZIP. Проверьте соединение и попробуйте снова.",
    create_app_failed: "Не удалось создать приложение",
    waiting_for_upload: "Ожидание загрузки",
    app_ready_needs_zip: "Это приложение готово, но требует загрузку ZIP файла. Перейдите в консоль разработчика для загрузки.",
    go_to_developer_console: "Перейти в консоль разработчика",
    got_it: "Понятно!",
    token_generation_failed_text: "Ошибка генерации токена. Проверьте вкладку API Tokens.",
    loading_profile: "Загрузка профиля...",
    developer_mode: "Режим разработчика",
    enable_developer_mode: "Включить режим разработчика",
    disable_developer_mode: "Отключить режим разработчика",
    select_language: "Язык",
    english: "Английский",
    russian: "Русский",
    profile: "Профиль",
    dev: "Разраб",
    delete_app: "Удалить приложение",
    app_deleted: "Приложение удалено",
    delete_failed: "Не удалось удалить",
    delete: "Удалить",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string) => {
    return (
      translations[language][key as keyof (typeof translations)["en"]] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
